spring:
  datasource:
    url: jdbc:postgresql://dpg-csmau0d6l47c73ep7h0g-a.oregon-postgres.render.com/hocasavar_api
    username: hocasavar_api_user
    password: z75o2MF1UDBUtqgx4KQXMmuV7pRhhaoP
    driver-class-name: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: 
    show-sql: true